// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "mattermost-autolink",
    "name": "Autolink",
    "description": "Automatically rewrite text matching a regular expression into a Markdown link.",
    "homepage_url": "https://github.com/mattermost-community/mattermost-plugin-autolink",
    "support_url": "https://github.com/mattermost-community/mattermost-plugin-autolink/issues",
    "icon_path": "assets/icon.svg",
    "version": "0.0.0+448c8d4",
    "min_server_version": "5.16.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Configure this plugin directly in the config.json file, or using the /autolink command. Learn more [in our documentation](https://github.com/mattermost-community/mattermost-plugin-autolink/blob/master/README.md).\\n\\n To report an issue, make a suggestion, or contribute, [check the plugin repository](https://github.com/mattermost-community/mattermost-plugin-autolink).",
        "footer": "",
        "settings": [
            {
                "key": "enableadmincommand",
                "display_name": "Enable administration with /autolink command:",
                "type": "bool",
                "help_text": "",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "enableonupdate",
                "display_name": "Apply plugin to updated posts as well as new posts:",
                "type": "bool",
                "help_text": "",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            },
            {
                "key": "pluginmanagers",
                "display_name": "Plugin Managers:",
                "type": "text",
                "help_text": "Comma-separated list of usernames who manage autolink requests. These users will always receive DM notifications when new requests are submitted (even if they are the submitter), and are authorized to administer the plugin via slash commands.",
                "placeholder": "admin, johndoe",
                "default": null,
                "hosting": "",
                "secret": false
            },
            {
                "key": "enableusersubmissions",
                "display_name": "Enable User Submissions:",
                "type": "bool",
                "help_text": "Allow non-admin users to submit autolink pattern requests via /autolink-request command. Admins will be notified via DM when new requests are submitted.",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "maxsubmissionsperuser",
                "display_name": "Max Submissions Per User:",
                "type": "number",
                "help_text": "Maximum number of pending submissions allowed per user (0 = unlimited). This helps prevent spam while allowing legitimate requests.",
                "placeholder": "0",
                "default": 0,
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export const PLUGIN_ID = manifest.id;

export default manifest;
